version: "3.8"

services:
  chopchopsplit:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGO_URI
        - BOT_TOKEN
        - APP_HOST
        - APP_PORT
        - GEMINI_API_KEY
    user: "node"
    environment:
      - NODE_ENV=production
      - TZ=Europe/Rome
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${APP_PORT:-3000}:3000